apiVersion: v1
kind: ConfigMap
metadata:
  name: index-html-configmap
  namespace: ns-bsbm-o-sre-playground 
data:
  index.html: |
    <html>
      <head>
        <title>Hello from Nginx in OpenShift</title>
      </head>
      <body>
        <h1>Hello world from Klaas!</h1>
        <p>Desperatly learning Kubernetes, OpenShift, ArgoCD, Azure and more...</p>
      </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: ns-bsbm-o-sre-playground
  labels:
    app: nginx
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginxinc/nginx-unprivileged:stable-bookworm-perl
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config-volume-nginx
          mountPath: /usr/share/nginx/html

      volumes:
      - name: config-volume-nginx
        configMap:
          name: index-html-configmap

